name: Continous Integration

on: [push, pull_request]

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut to VM
              uses: actions/checkout@v3

            - name: Run Linter
              uses: devcontainers/ci@v0.3
              with:
                push: never
                runCmd: |
                    pdm sync
                    pdm check
    type_checker:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut to VM
              uses: actions/checkout@v3

            - name: Run Type Checker
              uses: devcontainers/ci@v0.3
              with:
                push: never
                runCmd: |
                    pdm sync
                    pdm mypy
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: CheckOut to VM
              uses: actions/checkout@v3

            - name: Run Tests
              uses: devcontainers/ci@v0.3
              with:
                push: never
                runCmd: |
                    pdm sync
                    pdm tests
